# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e840b7fca70505b7e6fa8ce934a5bb8385adfb29b351d9d834d05e3d3ab4edbef1d8eee8c556b27932363b377144f345404311ffba6558a13e2c89cfea5827b5

test:
  secret_key_base: de64d06c6834c3f599a00b36f10086b2c9fee8d6dc2c6063c995c30e9e7e9bc865e11075b80e14d03c41dd7975a93ca0e9e659f4ab82025c6da39b16b6801fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
